import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  METRIC_NAMES,
  METRIC_UNITS,
  type Device,
  type EventMarker,
  type MetricEvent,
  type Session,
  type Target
} from "@lumatrace/core";
import {
  DeviceRepository,
  MarkerRepository,
  MetricRepository,
  LumaTraceDatabase,
  ReportRepository,
  SessionRepository,
  TargetRepository
} from "@lumatrace/storage";
import { DEFAULT_REPORT_LOCALIZATION, ReportGenerator, type ReportInput } from "../src";

function device(): Device {
  return {
    id: "device-1",
    platform: "windows",
    name: "Report Device",
    connectionType: "local",
    capabilities: [
      {
        metricName: "fps",
        platform: "windows",
        status: "experimental",
        source: "mock",
        reason: "Generated by test"
      }
    ]
  };
}

function target(): Target {
  return {
    id: "target-1",
    name: "Report Target",
    type: "game",
    platform: "windows"
  };
}

function session(): Session {
  return {
    id: "session-1",
    name: "Report Session",
    deviceId: "device-1",
    targetId: "target-1",
    startedAt: 1000,
    endedAt: 4000,
    sampleIntervalMs: 1000,
    status: "stopped"
  };
}

function metric(overrides: Partial<MetricEvent>): MetricEvent {
  return {
    sessionId: "session-1",
    timestampMs: 1000,
    monotonicMs: 0,
    sequence: 0,
    deviceId: "device-1",
    targetId: "target-1",
    metricName: METRIC_NAMES.FPS,
    value: 60,
    unit: METRIC_UNITS.FPS,
    source: "mock",
    precision: "estimated",
    confidence: "high",
    tags: {
      refreshRate: 60,
      profileName: "report-test"
    },
    ...overrides
  };
}

function metrics(): MetricEvent[] {
  return [
    metric({
      timestampMs: 1000,
      sequence: 0,
      metricName: METRIC_NAMES.FPS,
      unit: METRIC_UNITS.FPS,
      value: 60
    }),
    metric({
      timestampMs: 2000,
      sequence: 1,
      metricName: METRIC_NAMES.FPS,
      unit: METRIC_UNITS.FPS,
      value: 30
    }),
    metric({
      timestampMs: 3000,
      sequence: 2,
      metricName: METRIC_NAMES.FPS,
      unit: METRIC_UNITS.FPS,
      value: 20
    }),
    metric({
      timestampMs: 1000,
      sequence: 3,
      metricName: METRIC_NAMES.FRAME_TIME_MS,
      unit: METRIC_UNITS.MILLISECONDS,
      value: 16
    }),
    metric({
      timestampMs: 2000,
      sequence: 4,
      metricName: METRIC_NAMES.FRAME_TIME_MS,
      unit: METRIC_UNITS.MILLISECONDS,
      value: 34
    }),
    metric({
      timestampMs: 3000,
      sequence: 5,
      metricName: METRIC_NAMES.FRAME_TIME_MS,
      unit: METRIC_UNITS.MILLISECONDS,
      value: 51
    }),
    metric({
      timestampMs: 1000,
      sequence: 6,
      metricName: METRIC_NAMES.CPU_PERCENT,
      unit: METRIC_UNITS.PERCENT,
      value: 160,
      tags: { normalizedPercent: 20, rawPercent: 160, coreCount: 8 }
    }),
    metric({
      timestampMs: 2000,
      sequence: 7,
      metricName: METRIC_NAMES.CPU_PERCENT,
      unit: METRIC_UNITS.PERCENT,
      value: 400,
      tags: { normalizedPercent: 50, rawPercent: 400, coreCount: 8 }
    }),
    metric({
      timestampMs: 1000,
      sequence: 8,
      metricName: METRIC_NAMES.MEMORY_MB,
      unit: METRIC_UNITS.MEGABYTES,
      value: 500
    }),
    metric({
      timestampMs: 2000,
      sequence: 9,
      metricName: METRIC_NAMES.MEMORY_MB,
      unit: METRIC_UNITS.MEGABYTES,
      value: 550
    })
  ];
}

function marker(): EventMarker {
  return {
    id: "marker-1",
    sessionId: "session-1",
    timestampMs: 1500,
    label: "Start"
  };
}

function input(): ReportInput {
  return {
    session: session(),
    device: device(),
    target: target(),
    metrics: metrics(),
    markers: [marker()],
    generatedAt: 10,
    toolStatus: [{ toolName: "adb", status: "missing", reason: "not needed for mock" }]
  };
}

function seedStorage(database: LumaTraceDatabase): void {
  new DeviceRepository(database).upsert(device());
  new TargetRepository(database).upsert("device-1", target());
  new SessionRepository(database).create(session());
  new MetricRepository(database).insertRawBatch(metrics());
  new MarkerRepository(database).create(marker());
}

describe("ReportGenerator", () => {
  it("renders HTML with the selected report localization", () => {
    const report = new ReportGenerator().generate(input(), {
      localization: {
        ...DEFAULT_REPORT_LOCALIZATION,
        locale: "zh-CN",
        strings: {
          ...DEFAULT_REPORT_LOCALIZATION.strings,
          title: "测试结果",
          summary: "核心指标",
          localData: "数据保存在本机。"
        },
        summaryLabels: {
          ...DEFAULT_REPORT_LOCALIZATION.summaryLabels,
          avgFps: "平均 FPS"
        }
      }
    });

    expect(report.html).toContain('<html lang="zh-CN" dir="ltr">');
    expect(report.html).toContain("LumaTrace · 测试结果");
    expect(report.html).toContain("核心指标");
    expect(report.html).toContain("平均 FPS");
    expect(report.html).not.toContain("数据保存在本机。");
    expect(JSON.parse(report.json)).toMatchObject({ locale: "zh-CN" });
  });

  it("uses report localization stored with the session", () => {
    const localizedSession = {
      ...session(),
      config: {
        reportLocalization: {
          ...DEFAULT_REPORT_LOCALIZATION,
          locale: "ja-JP",
          strings: {
            ...DEFAULT_REPORT_LOCALIZATION.strings,
            title: "テスト結果"
          }
        }
      }
    };
    const report = new ReportGenerator().generate({ ...input(), session: localizedSession });

    expect(report.html).toContain('<html lang="ja-JP" dir="ltr">');
    expect(report.html).toContain("LumaTrace · テスト結果");
  });

  it("generates summary/json/csv/html from mock metrics", () => {
    const report = new ReportGenerator().generate(input(), {
      includeRawMetricsInHtml: true
    });

    expect(report.summary.durationMs).toBe(3000);
    expect(report.summary.avgFps).toBeCloseTo(36.67, 2);
    expect(report.summary.jankCount).toBe(2);
    expect(report.summary.severeJankCount).toBe(1);
    expect(report.summary.avgCpuPercent).toBe(35);
    expect(report.summary.peakCpuPercent).toBe(50);
    expect(report.summary.peakMemoryMb).toBe(550);
    expect(report.summary.networkRxMb).toBeUndefined();
    expect(report.rawMetricCount).toBe(metrics().length);
    expect(JSON.parse(report.json)).toMatchObject({ version: "mvp-a" });
    expect(report.csv).toContain("timestampMs,monotonicMs,sequence");
    expect(report.html).toContain("LumaTrace · Test Results");
    expect(report.html).toContain("FPS Analysis");
    expect(report.html).toContain("1% Low FPS:</strong> 20 fps");
  });

  it("uses metric timestamp range when session duration is incomplete and does not fake missing metrics", () => {
    const incompleteSession: Session = {
      id: "session-1",
      name: "Report Session",
      deviceId: "device-1",
      targetId: "target-1",
      sampleIntervalMs: 1000,
      status: "stopped"
    };
    const report = new ReportGenerator().generate({
      ...input(),
      session: incompleteSession,
      metrics: [metric({ timestampMs: 1000 }), metric({ timestampMs: 2500, sequence: 1 })]
    });

    expect(report.summary.durationMs).toBe(1500);
    expect(report.summary.avgMemoryMb).toBeUndefined();
    expect(report.summary.networkRxMb).toBeUndefined();
    expect(report.summary.batteryDrainPercent).toBeUndefined();
  });

  it("summarizes network byte deltas without treating missing network as zero", () => {
    const report = new ReportGenerator().generate({
      ...input(),
      metrics: [
        metric({
          timestampMs: 2000,
          sequence: 1,
          metricName: METRIC_NAMES.NETWORK_RX_BYTES,
          unit: METRIC_UNITS.BYTES,
          value: 1024 * 1024,
          source: "adb:/proc/net/dev",
          precision: "device_level",
          confidence: "low",
          tags: { intervalMs: 1000, scope: "device" }
        }),
        metric({
          timestampMs: 2000,
          sequence: 2,
          metricName: METRIC_NAMES.NETWORK_TX_BYTES,
          unit: METRIC_UNITS.BYTES,
          value: 512 * 1024,
          source: "adb:/proc/net/dev",
          precision: "device_level",
          confidence: "low",
          tags: { intervalMs: 1000, scope: "device" }
        })
      ]
    });

    expect(report.summary.networkRxMb).toBe(1);
    expect(report.summary.networkTxMb).toBe(0.5);
    expect(report.summary.avgFps).toBeUndefined();
  });

  it("summarizes Windows GPU, power, and CPU/GPU temperatures independently", () => {
    const report = new ReportGenerator().generate({
      ...input(),
      metrics: [
        metric({ metricName: METRIC_NAMES.GPU_UTILIZATION, unit: METRIC_UNITS.PERCENT, value: 20 }),
        metric({ metricName: METRIC_NAMES.GPU_UTILIZATION, unit: METRIC_UNITS.PERCENT, value: 60 }),
        metric({ metricName: METRIC_NAMES.POWER_W, unit: METRIC_UNITS.WATTS, value: 40 }),
        metric({ metricName: METRIC_NAMES.POWER_W, unit: METRIC_UNITS.WATTS, value: 80 }),
        metric({
          metricName: METRIC_NAMES.CPU_TEMPERATURE_C,
          unit: METRIC_UNITS.CELSIUS,
          value: 50
        }),
        metric({
          metricName: METRIC_NAMES.CPU_TEMPERATURE_C,
          unit: METRIC_UNITS.CELSIUS,
          value: 70
        }),
        metric({
          metricName: METRIC_NAMES.GPU_TEMPERATURE_C,
          unit: METRIC_UNITS.CELSIUS,
          value: 45
        }),
        metric({
          metricName: METRIC_NAMES.GPU_TEMPERATURE_C,
          unit: METRIC_UNITS.CELSIUS,
          value: 65
        })
      ]
    });

    expect(report.summary.avgGpuPercent).toBe(40);
    expect(report.summary.peakGpuPercent).toBe(60);
    expect(report.summary.avgPowerW).toBe(60);
    expect(report.summary.peakPowerW).toBe(80);
    expect(report.summary.avgCpuTemperatureC).toBe(60);
    expect(report.summary.peakCpuTemperatureC).toBe(70);
    expect(report.summary.avgGpuTemperatureC).toBe(55);
    expect(report.summary.peakGpuTemperatureC).toBe(65);
    expect(report.summary.peakTemperatureC).toBeUndefined();
    expect(report.html).not.toContain("CPU Temperature");
    expect(report.html).toContain("Peak GPU Temperature");
  });

  it("does not summarize CPU temperatures from the withdrawn ACPI zone classifier", () => {
    const report = new ReportGenerator().generate({
      ...input(),
      metrics: [
        metric({
          metricName: METRIC_NAMES.CPU_TEMPERATURE_C,
          unit: METRIC_UNITS.CELSIUS,
          value: 27.85,
          source: "windows:acpi-processor-thermal-zone"
        })
      ]
    });

    expect(report.summary.avgCpuTemperatureC).toBeUndefined();
    expect(report.summary.peakCpuTemperatureC).toBeUndefined();
  });

  it("generates from storage and saves report cache when requested", () => {
    const database = new LumaTraceDatabase({ dbPath: ":memory:" });
    seedStorage(database);
    const reportRepository = new ReportRepository(database);

    try {
      const report = new ReportGenerator({
        reportRepository,
        metricRepository: new MetricRepository(database),
        markerRepository: new MarkerRepository(database),
        sessionRepository: new SessionRepository(database),
        deviceRepository: new DeviceRepository(database),
        targetRepository: new TargetRepository(database)
      }).generateFromStorage("session-1", { saveToRepository: true });

      expect(report.summary.avgFps).toBeCloseTo(36.67, 2);
      expect(reportRepository.get("session-1")?.summary.avgFps).toBeCloseTo(36.67, 2);
    } finally {
      database.close();
    }
  });

  it("writes json/csv/html files to a sanitized temp path", async () => {
    const outputDir = await mkdtemp(join(tmpdir(), "lumatrace-report-"));
    const generator = new ReportGenerator();

    try {
      const report = generator.generate(input());
      const paths = await generator.writeFiles(report, {
        outputDir,
        fileBaseName: "../unsafe/session"
      });

      expect(paths.jsonPath?.endsWith("_unsafe_session.json")).toBe(true);
      expect(await readFile(paths.jsonPath ?? "", "utf8")).toContain('"version": "mvp-a"');
      expect(await readFile(paths.csvPath ?? "", "utf8")).toContain("timestampMs");
      expect(await readFile(paths.htmlPath ?? "", "utf8")).toContain("<!doctype html>");
    } finally {
      await rm(outputDir, { recursive: true, force: true });
    }
  });
});
