import {
  CollectorError,
  METRIC_NAMES,
  type Device,
  type MetricAvailability,
  type MetricEvent,
  type MetricCollector,
  type Platform,
  type Session,
  type SessionConfig,
  type Target
} from "@lumatrace/core";
import { MockSessionRuntime } from "./mockSessionRuntime";
import {
  DEFAULT_MOCK_PROFILE_NAME,
  getMockProfile,
  type MockMetricProfile,
  type MockProfileName
} from "./mockProfiles";

export interface MockCollectorOptions {
  seed?: string | number;
  immediate?: boolean;
}

const MOCK_DEVICE_ID = "mock-local-device-1";
const MOCK_PLATFORM: Platform = "windows";
const MOCK_CAPABILITY_REASON = "Generated by MockCollector for development and tests";

const MOCK_CAPABILITIES: MetricAvailability[] = [
  METRIC_NAMES.FPS,
  METRIC_NAMES.FRAME_TIME_MS,
  METRIC_NAMES.CPU_PERCENT,
  METRIC_NAMES.MEMORY_MB
].map((metricName) => ({
  metricName,
  platform: MOCK_PLATFORM,
  status: metricName === METRIC_NAMES.FPS ? "experimental" : "available",
  reason: MOCK_CAPABILITY_REASON,
  source: "mock"
}));

const MOCK_TARGETS: Target[] = [
  {
    id: "mock-game",
    name: "Mock Game",
    type: "game",
    platform: MOCK_PLATFORM,
    pid: 4242,
    executablePath: "C:\\LumaTrace\\MockGame.exe",
    tags: {
      source: "mock",
      profileName: "janky_game"
    }
  },
  {
    id: "mock-app",
    name: "Mock App",
    type: "app",
    platform: MOCK_PLATFORM,
    pid: 4343,
    executablePath: "C:\\LumaTrace\\MockApp.exe",
    tags: {
      source: "mock",
      profileName: "stable_60fps"
    }
  }
];

function cloneCapabilities(): MetricAvailability[] {
  return MOCK_CAPABILITIES.map((capability) => ({ ...capability }));
}

function cloneDevice(): Device {
  return {
    id: MOCK_DEVICE_ID,
    platform: MOCK_PLATFORM,
    name: "Mock Local Device",
    osVersion: "Mock OS",
    connectionType: "local",
    capabilities: cloneCapabilities(),
    tags: {
      source: "mock"
    }
  };
}

function cloneTarget(target: Target): Target {
  const cloned: Target = {
    ...target,
  };

  if (target.tags !== undefined) {
    cloned.tags = { ...target.tags };
  }

  return cloned;
}

function readStringOption(config: SessionConfig, key: string): string | undefined {
  const optionValue = config.options?.[key];
  if (typeof optionValue === "string") {
    return optionValue;
  }

  const tagValue = config.tags?.[key];
  if (typeof tagValue === "string") {
    return tagValue;
  }

  return undefined;
}

function readBooleanOption(config: SessionConfig, key: string): boolean | undefined {
  const optionValue = config.options?.[key];
  if (typeof optionValue === "boolean") {
    return optionValue;
  }

  return undefined;
}

function readSeed(config: SessionConfig, fallback: string | number): string | number {
  const seed = config.options?.seed;
  if (typeof seed === "string" || typeof seed === "number") {
    return seed;
  }

  return fallback;
}

function createSessionConfigSnapshot(
  config: SessionConfig,
  profile: MockMetricProfile,
  seed: string | number
): Record<string, unknown> {
  return {
    profileName: profile.name,
    seed,
    requestedMetrics: [...(config.metrics ?? [])],
    options: { ...(config.options ?? {}) },
    tags: { ...(config.tags ?? {}) }
  };
}

export class MockCollector implements MetricCollector {
  readonly id = "mock";
  readonly platform = MOCK_PLATFORM;

  private readonly seed: string | number;
  private readonly immediate: boolean;
  private readonly runtimes = new Map<string, MockSessionRuntime>();
  private sessionCounter = 0;

  constructor(options: MockCollectorOptions = {}) {
    this.seed = options.seed ?? "lumatrace-mock";
    this.immediate = options.immediate ?? false;
  }

  async discoverDevices(): Promise<Device[]> {
    return [cloneDevice()];
  }

  async listTargets(deviceId: string): Promise<Target[]> {
    this.assertDeviceExists(deviceId);
    return MOCK_TARGETS.map((target) => cloneTarget(target));
  }

  async getCapabilities(deviceId?: string): Promise<MetricAvailability[]> {
    if (deviceId !== undefined) {
      this.assertDeviceExists(deviceId);
    }

    return cloneCapabilities();
  }

  async startSession(config: SessionConfig): Promise<Session> {
    this.assertDeviceExists(config.deviceId);
    this.assertTargetExists(config.deviceId, config.targetId);

    const sessionId = config.id ?? this.createSessionId();
    const existingRuntime = this.runtimes.get(sessionId);
    if (existingRuntime !== undefined) {
      if (existingRuntime.status === "running") {
        throw new CollectorError("Mock session is already running.", "SESSION_ALREADY_RUNNING", {
          collectorId: this.id,
          sessionId
        });
      }

      return existingRuntime.resume();
    }

    const profileName = readStringOption(config, "profileName") ?? DEFAULT_MOCK_PROFILE_NAME;
    const profile = getMockProfile(profileName);
    const sampleIntervalMs = config.sampleIntervalMs ?? profile.sampleIntervalMs ?? 1000;
    const seed = readSeed(config, this.seed);
    const immediate = readBooleanOption(config, "immediate") ?? this.immediate;
    const session: Session = {
      id: sessionId,
      name: config.name,
      deviceId: config.deviceId,
      targetId: config.targetId,
      startedAt: Date.now(),
      sampleIntervalMs,
      status: "running",
      config: createSessionConfigSnapshot(config, profile, seed)
    };

    const runtime = new MockSessionRuntime({
      session,
      profile,
      seed,
      immediate
    });
    this.runtimes.set(sessionId, runtime);

    return runtime.snapshot();
  }

  async pauseSession(sessionId: string): Promise<void> {
    this.getRuntimeOrThrow(sessionId).pause();
  }

  async stopSession(sessionId: string): Promise<void> {
    this.getRuntimeOrThrow(sessionId).stop();
  }

  streamMetrics(sessionId: string): AsyncIterable<MetricEvent> {
    return this.getRuntimeOrThrow(sessionId).stream();
  }

  getSessionSnapshot(sessionId: string): Session | undefined {
    return this.runtimes.get(sessionId)?.snapshot();
  }

  private assertDeviceExists(deviceId: string): void {
    if (deviceId !== MOCK_DEVICE_ID) {
      throw new CollectorError("Mock device does not exist.", "DEVICE_NOT_FOUND", {
        collectorId: this.id,
        deviceId
      });
    }
  }

  private assertTargetExists(deviceId: string, targetId: string): void {
    this.assertDeviceExists(deviceId);
    if (!MOCK_TARGETS.some((target) => target.id === targetId)) {
      throw new CollectorError("Mock target does not exist.", "TARGET_NOT_FOUND", {
        collectorId: this.id,
        deviceId,
        targetId
      });
    }
  }

  private getRuntimeOrThrow(sessionId: string): MockSessionRuntime {
    const runtime = this.runtimes.get(sessionId);
    if (runtime === undefined) {
      throw new CollectorError("Mock session does not exist.", "SESSION_NOT_FOUND", {
        collectorId: this.id,
        sessionId
      });
    }

    return runtime;
  }

  private createSessionId(): string {
    this.sessionCounter += 1;
    return `mock-session-${this.sessionCounter}`;
  }
}

export type { MockProfileName };
